language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '12'
  - '13'
jobs:
  include:
    - stage: compile
      script: npx lerna run build
    - stage: test
      script: npx lerna run test:prod
    - stage: deploy
      node_js: 13
      script:
        - npx lerna run report-coverage
#        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx lerna run deploy-docs; fi
#        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx lerna run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
