language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '12'
  - '13'
script: npx lerna run test:prod && npx lerna run build
jobs:
  include:
    - stage: deploy
      node_js: 13
      script:
        - npx lerna run report-coverage
#        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx lerna run deploy-docs; fi
#        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx lerna run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
